// Generated by CoffeeScript 1.10.0
(function() {
  var dictionary, log;

  log = function(data) {
    return console.log(data);
  };

  dictionary = {
    syntax: {
      dot: {
        pattern: /\s?\|\s?/g,
        output: '.',
        process: function(part) {
          return part.replace(this.pattern, this.output);
        }
      },
      array: {
        pattern: /#(\d+)|(-)(-)?\d?/g,
        output: '[]',
        process: function(part) {
          var match;
          console.log("array");
          part = part.replace("#", "[");
          part = part.replace("-", "...");
          match = part.match(/(\d+\s)|((\.\.\.)?\d+)/g);
          part = part.replace(match, match + "]");
          return part;
        }
      },
      bOR: {
        pattern: /OR/g,
        output: '|',
        process: function(part) {
          return part.replace(this.pattern, this.output);
        }
      },
      bAND: {
        pattern: /AND/g,
        output: '&',
        process: function(part) {
          return part.replace(this.pattern, this.output);
        }
      }
    }
  };

  module.exports = dictionary;

}).call(this);
