// Generated by CoffeeScript 1.10.0
(function() {
  var Parser, log;

  log = function(data) {
    return console.log(data);
  };


  /* PARSER */

  Parser = (function() {
    var toDecimal;

    function Parser(dict) {
      this.dict = dict;
    }

    toDecimal = function(code) {
      return "_d" + code;
    };

    Parser.prototype.unicode = function(line) {
      var char, code, i, len, newLine;
      newLine = [];
      for (i = 0, len = line.length; i < len; i++) {
        char = line[i];
        code = char.charCodeAt(0);
        if (code > 256) {
          newLine.push(toDecimal(code));
        } else {
          newLine.push(char);
        }
      }
      return newLine.join("");
    };

    Parser.prototype.parse = function(line) {

      /*for entry, def of @dict.syntax
        line = line.replace def.pattern, def.output
      line
       */

      /* FIND NON-STRING SECTIONS */
      var def, end, entry, i, index, irrelevant, j, len, len1, match, parsed, part, pattern, positions, ref, section, sections, start;
      pattern = /'|"/g;
      positions = [0];
      while (true) {
        match = pattern.exec(line);
        if (match != null) {
          positions.push(match.index);
        } else {
          break;
        }
      }
      positions.push(line.length);
      sections = [];
      for (index = i = 0, len = positions.length; i < len; index = i += 2) {
        irrelevant = positions[index];
        start = positions[index];
        end = positions[index + 1];
        if (start !== end - 1) {
          sections.push({
            start: start,
            end: end
          });
        }
      }
      for (j = 0, len1 = sections.length; j < len1; j++) {
        section = sections[j];
        ref = this.dict.syntax;
        for (entry in ref) {
          def = ref[entry];
          part = line.slice(section.start, section.end);
          match = part.match(def.pattern);
          if (match != null) {
            parsed = def.process(part);
            line = line.replace(part, parsed);
          }
        }
      }
      line = this.unicode(line);
      return line;
    };

    return Parser;

  })();

  module.exports = Parser;

}).call(this);
