// Generated by CoffeeScript 1.10.0
(function() {
  var Parser, args, dictionary, filename, lines, log, parser, readline;

  readline = require("linebyline");

  args = require("yargs").argv._;

  dictionary = require("./js/dictionary");

  Parser = require("./js/parser");

  parser = new Parser(dictionary);

  filename = args[0];

  lines = readline(filename);

  log = function(data) {
    return console.log(data);
  };

  lines.on('line', function(line, count) {
    return log(parser.parse(line));
  });

}).call(this);
