// Generated by CoffeeScript 1.10.0

/* NON-LATIN ALPHABETS */

(function() {
  var _u1593_u1588_u1608_u1575_u1574_u1610, _u38543_u26426, _u5846_u5809_u5796, _u8721, _u966, farm, i, len, num, x;

  _u1593_u1588_u1608_u1575_u1574_u1610 = Math.random();

  _u38543_u26426 = Math.random();


  /* MATH */

  _u8721 = 0;

  for (i = 0, len = series.length; i < len; i++) {
    num = series[i];
    _u8721 += num;
  }

  _u966 = 10;

  x = r(cos(_u966));


  /* UNITS */

  product.price = {
    $: 10,
    _u8364: 9.1,
    _u163: 6.7,
    _u165: 1209
  };

  room.dimensions = {
    length: 3,
    width: 3,
    height: 2,
    m_u178: 9,
    m_u179: 18
  };


  /* RANDOM */

  _u5846_u5809_u5796 = '_u5796_u5796_u5796';

  farm = {
    _u55357_u56324: 12,
    _u55357_u56337: 8,
    _u55357_u56339: 1,
    _u55357_u56340: 8
  };

}).call(this);
