// Generated by CoffeeScript 1.10.0

/* THIS MODULE IS CURRENTLY NOT USED! */

(function() {
  var dictionary, log;

  log = function(data) {
    return console.log(data);
  };

  dictionary = {
    log: {
      pattern: /(^|\s)log /,
      output: "console.log ",
      process: function(part) {
        return part.replace(this.pattern, this.output);
      }
    }
  };

  module.exports = dictionary;

}).call(this);
