// Generated by CoffeeScript 1.10.0
(function() {
  var $_d8594_d8364, _d8721, _d9787, _d9833, _d9834, blog, gamepad, i, len, num, price, series;

  price = {
    $: 10,
    _d8364: 9.1,
    _d163: 6.7,
    _d165: 1209
  };

  log(price);

  blog = {
    post: {
      _d9829: 4
    }
  };

  blog.post._d9829 += 1;

  log("Likes: " + blog.post._d9829);

  $_d8594_d8364 = function(input) {
    return input * 10 / 9;
  };

  log($_d8594_d8364(10));

  gamepad = {
    _d8592: false,
    _d8595: true,
    _d8600: true,
    _d8594: true
  };

  _d9787 = {};

  _d9787.crouch = function() {
    return log("crouching...");
  };

  if (gamepad._d8595) {
    _d9787.crouch();
  }

  series = [1, 2, 3, 4];

  _d8721 = 0;

  for (i = 0, len = series.length; i < len; i++) {
    num = series[i];
    _d8721 += num;
  }

  log(_d8721);

  _d9834 = function(note) {
    return log("Playing " + note + " for 0.05 seconds");
  };

  _d9833 = function(note) {
    return log("Playing " + note + " for 0.1 seconds");
  };

  _d9834('C');

  _d9834('E');

  _d9833('G');

}).call(this);
