// Generated by CoffeeScript 1.10.0
(function() {
  var Parser, args, colors, dictionary, error, filename, fs, lines, log, parsed, parser, readline;

  readline = require("linebyline");

  colors = require("colors");

  fs = require("fs");

  args = require("yargs").argv._;

  dictionary = require("./dictionary");

  Parser = require("./parser");

  log = function(data) {
    return console.log(data);
  };

  error = function(data) {
    return console.error(data.red);
  };

  parser = new Parser(dictionary);

  filename = {};

  if (args[0] != null) {
    filename.input = args[0];
  } else {
    error("Error: no input file");
    return;
  }

  if (args[1] != null) {
    filename.output = args[1];
  }

  lines = readline(filename.input);

  parsed = [];

  lines.on('error', function(err) {
    return error("Error: could not read file");
  });

  lines.on('line', function(line, count) {
    return parsed.push(parser.parse(line));
  });

  lines.on('end', function() {
    var output;
    output = parsed.join("\n") + "\n";
    if (filename.output != null) {
      return fs.writeFileSync(filename.output, output, 'utf8');
    } else {
      return log(output);
    }
  });

}).call(this);
